# Generated by Django 5.0.2 on 2024-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=100)),
                ('reputation', models.IntegerField()),
                ('group', models.CharField(default='', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('privilege_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Regular_Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('privilege_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Super_Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('privilege_level', models.IntegerField(default=2)),
            ],
        ),
    ]
