# Generated by Django 5.0.2 on 2024-02-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='')),
                ('comment_username', models.CharField(default='', max_length=50)),
                ('comment_itemid', models.IntegerField()),
                ('comment_times', models.CharField(default='0000-00-00 00:00', max_length=50)),
            ],
        ),
    ]
