# Generated by Django 5.0.2 on 2024-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('item_code', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('numbers', models.IntegerField()),
                ('approval_classification', models.IntegerField()),
                ('times', models.CharField(default='0000-00-00 00:00', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('item_code', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('numbers', models.IntegerField()),
                ('location', models.CharField(default='', max_length=100)),
                ('approval_classification', models.IntegerField()),
                ('times', models.CharField(default='0000-00-00 00:00', max_length=50)),
            ],
        ),
    ]
