# Generated by Django 5.0.2 on 2024-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_outbound_reason_outbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='frequency_use',
            field=models.IntegerField(default=0),
        ),
    ]
