# Generated by Django 5.0.2 on 2024-02-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_alter_items_frequency_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousing',
            name='approval_classification',
            field=models.IntegerField(default=0),
        ),
    ]
