# Generated by Django 5.0.2 on 2024-02-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('adminname', models.CharField(default='', max_length=50)),
                ('times', models.CharField(default='0000-00-00 00:00', max_length=50)),
            ],
        ),
    ]
