# Generated by Django 5.0.2 on 2024-03-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenduser_realname', models.CharField(default='', max_length=50)),
                ('lenditem_id', models.IntegerField(default=0)),
                ('lenditem_name', models.CharField(default='', max_length=50)),
                ('lendnumber', models.IntegerField(default=0)),
                ('lenditem_grade', models.IntegerField(default=0)),
                ('lendtime', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('lendday', models.IntegerField(default=0)),
                ('approval_progress', models.CharField(default='0%', max_length=50)),
                ('approved_adminname', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenduser_realname', models.CharField(default='', max_length=50)),
                ('lenditem_id', models.IntegerField(default=0)),
                ('lenditem_name', models.CharField(default='', max_length=50)),
                ('lendnumber', models.IntegerField(default=0)),
                ('lenditem_grade', models.IntegerField(default=0)),
                ('lendtime', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('lendday', models.IntegerField(default=0)),
                ('static', models.CharField(default='审核中', max_length=50)),
                ('lend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Function.lend')),
            ],
        ),
    ]
