# Generated by Django 5.0.2 on 2024-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0002_lend_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_realname', models.CharField(default='', max_length=50)),
                ('item_id', models.IntegerField(default=0)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('time', models.CharField(default='0000-00-00 00:00', max_length=50)),
            ],
        ),
    ]
