# Generated by Django 5.0.2 on 2024-03-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0003_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('user_realname', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
