# Generated by Django 5.0.2 on 2024-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0004_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='user_realname',
        ),
        migrations.AddField(
            model_name='collections',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
