# Generated by Django 5.0.2 on 2024-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0005_remove_collections_user_realname_collections_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='userid',
        ),
        migrations.AddField(
            model_name='collections',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
