# Generated by Django 5.0.2 on 2024-03-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0007_feedback_repairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('identity', models.CharField(default='', max_length=10)),
                ('times', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('HelpCenterid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HelpCenterSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsttext', models.TextField(default='')),
                ('userid', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=50)),
                ('handleadminid', models.IntegerField(default=0)),
                ('handleadmin', models.CharField(default='', max_length=50)),
                ('times', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('statics', models.BooleanField(default=False)),
            ],
        ),
    ]
