# Generated by Django 5.0.2 on 2024-03-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0008_helpcentercontent_helpcentersave'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('adress', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=50)),
                ('begintime', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('longtime', models.IntegerField(default=0)),
                ('item_grade', models.IntegerField(default=0)),
                ('approval_progress', models.CharField(default='0%', max_length=50)),
                ('approved_adminname', models.IntegerField(default=-1)),
            ],
        ),
    ]
