# Generated by Django 5.0.2 on 2024-03-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0009_equipmenttimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('adress', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=50)),
                ('begintime', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('longtime', models.IntegerField(default=0)),
                ('item_grade', models.IntegerField(default=0)),
                ('approval_progress', models.CharField(default='0%', max_length=50)),
                ('equipmenttimes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Function.equipmenttimes')),
            ],
        ),
    ]
