# Generated by Django 5.0.2 on 2024-03-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0010_equipmentapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('time24', models.BooleanField(default=False)),
                ('time1', models.BooleanField(default=False)),
                ('time2', models.BooleanField(default=False)),
                ('time3', models.BooleanField(default=False)),
                ('time4', models.BooleanField(default=False)),
                ('time5', models.BooleanField(default=False)),
                ('time6', models.BooleanField(default=False)),
                ('time7', models.BooleanField(default=False)),
                ('time8', models.BooleanField(default=False)),
                ('time9', models.BooleanField(default=False)),
                ('time10', models.BooleanField(default=False)),
                ('time11', models.BooleanField(default=False)),
                ('time12', models.BooleanField(default=False)),
                ('time13', models.BooleanField(default=False)),
                ('time14', models.BooleanField(default=False)),
                ('time15', models.BooleanField(default=False)),
                ('time16', models.BooleanField(default=False)),
                ('time17', models.BooleanField(default=False)),
                ('time18', models.BooleanField(default=False)),
                ('time19', models.BooleanField(default=False)),
                ('time20', models.BooleanField(default=False)),
                ('time21', models.BooleanField(default=False)),
                ('time22', models.BooleanField(default=False)),
                ('time23', models.BooleanField(default=False)),
            ],
        ),
    ]
