# Generated by Django 5.0.2 on 2024-03-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0011_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time24',
            new_name='time0',
        ),
    ]
