# Generated by Django 5.0.2 on 2024-03-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0012_rename_time24_appointment_time0'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='0000-00-00', max_length=50),
        ),
    ]
