# Generated by Django 5.0.2 on 2024-03-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0013_appointment_day_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentapproval',
            name='approval_progress',
            field=models.BooleanField(default=False),
        ),
    ]
