# Generated by Django 5.0.2 on 2024-03-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0014_alter_equipmentapproval_approval_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmenttimes',
            old_name='approved_adminname',
            new_name='privilege_level',
        ),
    ]
