# Generated by Django 5.0.2 on 2024-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0015_rename_approved_adminname_equipmenttimes_privilege_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('times', models.CharField(default='0000-00-00 00:00', max_length=50)),
                ('notname', models.CharField(default='', max_length=50)),
                ('oread', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens', models.IntegerField(default=0)),
                ('tf', models.BooleanField(default=False)),
            ],
        ),
    ]
