# Generated by Django 5.0.2 on 2024-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0016_newnotifications_ornews'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='oread',
            field=models.BooleanField(default=False),
        ),
    ]
