# Generated by Django 5.0.2 on 2024-03-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0017_notice_oread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='ns',
            field=models.CharField(default='', max_length=50),
        ),
    ]
