# Generated by Django 5.0.2 on 2024-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0018_notice_ns'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttimes',
            name='oretuen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lend',
            name='oretuen',
            field=models.BooleanField(default=False),
        ),
    ]
