# Generated by Django 5.0.2 on 2024-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinaryuser',
            name='reputation',
            field=models.IntegerField(default=100),
        ),
    ]
